// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6bmZ2j-3RxKn8JjzU3mErPI6g2GxytpY',
    appId: '1:605548952316:web:014d3fe9d4f633a6fe7579',
    messagingSenderId: '605548952316',
    projectId: 'teachers-students-828d2',
    authDomain: 'teachers-students-828d2.firebaseapp.com',
    storageBucket: 'teachers-students-828d2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVxJ0qfwgfDiCgeKf0oDyWGws2eizLFfo',
    appId: '1:605548952316:android:cb428d8bba5ab3cafe7579',
    messagingSenderId: '605548952316',
    projectId: 'teachers-students-828d2',
    storageBucket: 'teachers-students-828d2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCe-l83WvflN8PBj2sePdB4b46Tgew01uw',
    appId: '1:605548952316:ios:04ca7d86d2cd7353fe7579',
    messagingSenderId: '605548952316',
    projectId: 'teachers-students-828d2',
    storageBucket: 'teachers-students-828d2.appspot.com',
    iosClientId: '605548952316-k1bvotf2lav59i6ngpch4r5ajnskpsf8.apps.googleusercontent.com',
    iosBundleId: 'com.example.myProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCe-l83WvflN8PBj2sePdB4b46Tgew01uw',
    appId: '1:605548952316:ios:ae81359ee9e9721ffe7579',
    messagingSenderId: '605548952316',
    projectId: 'teachers-students-828d2',
    storageBucket: 'teachers-students-828d2.appspot.com',
    iosClientId: '605548952316-dn1bat6u66pidunkdi8n4b516q2l7b65.apps.googleusercontent.com',
    iosBundleId: 'com.example.myProject.RunnerTests',
  );
}
